// TypeScript type definitions for database
// This file will be auto-generated by Supabase CLI in future stories
// For now, it serves as a placeholder

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // Tables will be defined in subsequent stories
    };
    Views: {
      // Views will be defined if needed
    };
    Functions: {
      // Functions will be defined if needed
    };
    Enums: {
      // Enums will be defined if needed
    };
  };
}
